name: mdtraj
channels:
  - conda-forge
  - https://conda.rosettacommons.org
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - attr=2.5.2=h39aace5_0
  - blosc=1.21.6=he440d0b_1
  - brotli=1.1.0=hb9d3cd8_3
  - brotli-bin=1.1.0=hb9d3cd8_3
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - c-blosc2=2.19.0=h3122c55_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - contourpy=1.3.3=py313h7037e92_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.16.2=h3c4dab8_0
  - double-conversion=3.3.1=h5888daf_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.59.1=py313h3dea7bd_0
  - freetype=2.14.1=ha770c72_0
  - glew=2.3.0=h71661d4_0
  - glib=2.86.0=he175458_0
  - glib-tools=2.86.0=hf516916_0
  - glm=1.0.1=hdd259ec_0
  - graphite2=1.3.14=hecca717_2
  - gst-plugins-base=1.24.11=h651a532_0
  - gstreamer=1.24.11=hc37bda9_0
  - harfbuzz=12.1.0=h15599e2_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h6e4c0c1_102
  - icu=75.1=he02047a_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.9=py313hc8edb43_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.4=h3f801dc_0
  - libblas=3.9.0=32_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcap=2.77=h3ff7636_0
  - libcblas=3.9.0=32_he106b2a_openblas
  - libclang-cpp20.1=20.1.8=default_hddf928d_0
  - libclang-cpp21.1=21.1.8=default_h99862b1_3
  - libclang13=21.1.8=default_h746c552_3
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.5.0=he200343_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgfortran=15.1.0=h69a702a_3
  - libgfortran5=15.1.0=hcea5267_3
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.0=h1fed272_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_3
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=32_h7ac8fdf_openblas
  - libllvm20=20.1.8=hf7376ad_1
  - libllvm21=21.1.8=hf7376ad_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnetcdf=4.9.3=nompi_h11f7409_103
  - libnghttp2=1.64.0=h161d5f1_0
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libopus=1.6.1=h280c20c_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.54=h421ea60_0
  - libpq=18.1=h5c52fec_2
  - libsndfile=1.2.2=hc7d488a_2
  - libsqlite=3.51.2=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libsystemd0=257.10=hd0affe5_3
  - libtiff=4.7.1=h8261f1e_0
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h54a6638_2
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.1=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxslt=1.1.43=h711ed8c_1
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - matplotlib=3.10.5=py313h78bf25f_0
  - matplotlib-base=3.10.5=py313h683a580_0
  - mdtraj=1.11.0=py313hf979834_1
  - mpg123=1.32.9=hc50e24c_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nomkl=1.0=h5ca1d4c_0
  - nspr=4.38=h29cc59b_0
  - nss=3.118=h445c969_0
  - numexpr=2.10.2=py313h5f97788_100
  - numpy=2.3.1=py313hf6604e3_1
  - openjpeg=2.5.3=h55fea9a_1
  - openldap=2.6.10=he970967_0
  - openssl=3.6.1=h35e630c_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.1=py313h08cd8bf_0
  - pcre2=10.46=h1321c63_0
  - pillow=11.3.0=py313h8db990d_0
  - pip=25.1.1=pyh145f28c_0
  - pixman=0.46.4=h54a6638_1
  - ply=3.11=pyhd8ed1ab_3
  - pmw=2.1.1=py313h78bf25f_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pulseaudio-client=17.0=h9a8bead_2
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pymol-open-source=3.1.0=py313hcecbf5a_6
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyqt=5.15.11=py313h938ae94_2
  - pyqt5-sip=12.17.0=py313h7033f15_2
  - pyside6=6.9.3=py313h85046ba_2
  - pytables=3.10.2=py313h49b9dc6_6
  - python=3.13.5=hec9711d_102_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=7_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.15=h3c3fd16_6
  - qt6-main=6.9.3=h5c1c036_1
  - readline=8.2=h8c095d6_2
  - scipy=1.16.0=py313h86fcf2b_0
  - setuptools=80.9.0=pyhff2d567_0
  - sip=6.10.0=py313h7033f15_1
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h8bd8927_1
  - tk=8.6.13=noxft_hd72426e_102
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.4.0=pyhcf101f3_0
  - tornado=6.5.2=py313h07c4f96_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - wayland=1.24.0=h3e06ad9_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.4=h7955e40_0
  - zstd=1.5.7=hb8e6e7a_2
prefix: /home/wesg/miniforge3/envs/mdtraj
